### PR TITLE
sudo is no longer required

### PR DESCRIPTION
**Pull request by hugovk**
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

### CODE REVIEW

**Comment by badrange** [comment]
Let's see what Travis reports..

**Comment by badrange** [comment]
What is the problem with "Travis CI - Branch", it's just showing "Expected — Waiting for status to be reported" - didn't help to update the branch here.

**Comment by badrange** [comment]
I think the "Travis CI - Branch" is not run since this change is coming from a pull request from a fork. I'll merge.

**Comment by hugovk** [comment]
And it's not unique to this change, it also happened on my other PRs, eg. https://github.com/City-of-Helsinki/kukkuu-ui/pull/143.

**Pull request merged**
