### PR TITLE
Update the translations for Lippupiste and Ticketmaster

### PR DESCRIPTION
**Pull request by nikomakela**
KK-1005.
Updated translations from the product owner.

Also synced the translations with the translation spreadsheet https://docs.google.com/spreadsheets/d/1b5qAamjhmSNiME3matBINaeyz8TvoRWVB6wU5HvKy4g/edit#gid=463423571

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr481.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-ui-pr481.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by karisal-anders** [comment]
@nikomakela Approved but kukkuu-ui-review is failing. Made the failed checks rerun, let's see if that helps. If it doesn't please would you try to check if there's some problem with the tests.

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-ui-pr481.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by nikomakela** [comment]
> @nikomakela Approved but kukkuu-ui-review is failing. Made the failed checks rerun, let's see if that helps. If it doesn't please would you check what's going on.
It seems like the Helsinki-tunnus login has changed. I will create a new ticket about that.

**Pull request merged**
