### PR TITLE
docs: remove create_superuser env variable

### PR DESCRIPTION
**Pull request by nikomakela**
KK-1167

### CODE REVIEW

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-local.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr560.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-ui-pr560.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-local.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr560.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-ui-pr560.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by karisal-anders — APPROVED** [review]

**Comment by nikomakela** [comment]
Note: the pipeline no longer runs the browser tests nor deploys the local Tunnistamo nor API (in purpose) https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines/pullrequest/8649 . We need to have a new auth server for those.

**Pull request merged**
