### PR TITLE
KK-1068 | fix: update Helsinki partner logo URLs

### PR DESCRIPTION
**Pull request by karisal-anders**
### fix: update Helsinki partner logo URLs

refs KK-1068

## Context

[KK-1068](https://helsinkisolutionoffice.atlassian.net/browse/KK-1068)

## Screenshots

[KK-1068]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-local.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-local.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr526.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-ui-pr526.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by nikomakela — APPROVED** [review]

**Pull request merged**
