### PR TITLE
fix: test env mode

### PR DESCRIPTION
**Pull request by melniiv**
## Context

[jira-id](https://helsinkisolutionoffice.atlassian.net/browse/<jira-id>)

### CODE REVIEW

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr605.dev.hel.ninja :laughing::tada::tada::tada:

**Review by nikomakela — APPROVED** [review]

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr605.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr605.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr605.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
