### PR TITLE
ci: add version information in the (Nginx) readiness probe

### PR DESCRIPTION
**Pull request by nikomakela**
KK-1002

Read the following environment variables that are set in the pipeline process and set them in the respond of the Nginx `/readiness` -probe:
- RELEASE
- APP_VERSION
- COMMITHASH
- BUILD_TIME
----
The result can be tested in https://kukkuu-ui-pr501.dev.hel.ninja/readiness

These pipeline changes are needed: https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines/pullrequest/6470

### CODE REVIEW

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr501.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-ui-pr501.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr501.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by nikomakela** [comment]
At this point, only the application version information is given. It can be tested here: https://kukkuu-ui-pr501.dev.hel.ninja/readiness and also locally by running the docker container for example with with `DOCKER_TARGET=production docker-compose up --build`.

image

These pipeline changes are needed: https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines/pullrequest/6470

- [ ] Serve the version information through the pipeline for the readiness probe

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr501.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr501.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr501.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-ui-pr501.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by nikomakela** [comment]
✅  Test result:
image

**Comment by karisal-anders** [comment]
Accessible using curl ✅:
```bash
$ curl https://kukkuu-ui-pr501.dev.hel.ninja/readiness -vvv
* processing: https://kukkuu-ui-pr501.dev.hel.ninja/readiness
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 20.71.66.83:443...
* Connected to kukkuu-ui-pr501.dev.hel.ninja (20.71.66.83) port 443
* schannel: disabled automatic use of client certificate
* using HTTP/1.x
> GET /readiness HTTP/1.1
> Host: kukkuu-ui-pr501.dev.hel.ninja
> User-Agent: curl/8.2.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Mon, 30 Oct 2023 10:20:35 GMT
< Content-Type: application/json
< Content-Length: 160
< Connection: keep-alive
< server: nginx/1.22.1
< strict-transport-security: max-age=31536000;includeSubDomains;preload
<
{ [160 bytes data]
100   160  100   160    0     0    928      0 --:--:-- --:--:-- --:--:--   941{ "status": "ok", "release": "", "packageVersion": "1.14.1", "commitHash": "6ff3fee7f7cbae829cd3e93e22742f962ee13604", "buildTime": "2023-10-30T09:28:27.000Z" }
* Connection #0 to host kukkuu-ui-pr501.dev.hel.ninja left intact
```

**Review by karisal-anders — APPROVED** [review]
Except that "release" is currently always empty this looks fine to me.

**Comment by nikomakela** [comment]
> ```shell
> curl https://kukkuu-ui-pr501.dev.hel.ninja/readiness -vvv
> ```

It should be populated (only) when a release-tag is made. It needs to be tested when making a release.

**Pull request merged**
