### PR TITLE
KK-1043 | refactor: remove "update-translations" script & helsinki-utils package

### PR DESCRIPTION
**Pull request by karisal-anders**
### refactor: remove "update-translations" script & helsinki-utils package

refs KK-1043

## Context

[KK-1043](https://helsinkisolutionoffice.atlassian.net/browse/KK-1043)

## Screenshots

[KK-1043]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr547.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-ui-pr547.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by nikomakela — APPROVED** [review]
Nice! :shipit: 
NOTE: There is exactly the same script in kukkuu-admin.

**Comment by karisal-anders** [comment]
> Nice! :shipit: NOTE: There is exactly the same script in kukkuu-admin.

Ah, another PR coming up!

**Comment by karisal-anders** [comment]
> > Nice! :shipit: NOTE: There is exactly the same script in kukkuu-admin.
> 
> Ah, another PR coming up!

See https://github.com/City-of-Helsinki/kukkuu-admin/pull/264

**Pull request merged**
