### PR TITLE
Migrate to Vite (copy from #493)

### PR DESCRIPTION
**Pull request by nikomakela**
KK-1040 KK-1017

The https://github.com/City-of-Helsinki/kukkuu-ui/pull/493 was merged too early and it was rolledback. The reason for this was that the Vite needs a new set of environment variables that are prefixed with "VITE_" (https://github.com/City-of-Helsinki/kukkuu-ui/pull/493#issuecomment-1772655747). This PR is just a recreation of that earlier PR that was accidentally merged, because in Github, the PRs cannot be unmerged.

----

Bases to the huge pile of upgrading and migration changes in https://github.com/City-of-Helsinki/kukkuu-ui/pull/492.

The Create React App (CRA) is deprecated. It is advised to replace the CRA with Vite.

The migration process is done by following the instructions from
https://www.robinwieruch.de/vite-create-react-app/:
- The index.html is moved from the `/public` to the root. The relative paths are migrated.
-  Vitest is installed and the configuration for testing-library is made

The Sass styles from HDS and the app itself needed a couple of aliases.

The new setup includes
- Vite instead of CRA
- Vitest with the Testing-library instead of Jest
- Typescript for Vite

More about this:
- https://blog.bitsrc.io/the-future-of-react-why-create-react-app-is-deprecated-and-hooks-are-the-future-83e8a087a325
- https://dev.to/ag2byte/create-react-app-is-officially-dead-h7o
- https://github.com/facebook/create-react-app/issues/13072

### CODE REVIEW

**Comment by nikomakela** [comment]
Note that the review environment will fail until the pipeline is configured to use env-variables prefixed with `VITE_` instead of `REACT_APP_`.

- [ ] Fix the pipeline configuration

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-local.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-local.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr496.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr496.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by nikomakela** [comment]
The Sonarcloud may need some configuration or new packages still

- [ ] Check and configure the Sonarcloud coverage report for the CI

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr496.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr496.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
