### PR TITLE
Fixes to my profile registration and edit forms

### PR DESCRIPTION
**Pull request by nikomakela**
KK-1072. KK-1109. KK-1110.

### Rename the "terms field" component to "checkbox field"

The terms field has nothing related to actual "agree the terms" feature, but it is a pure Formik supported checkbox field, that could be used much more commonly.

### Show a toast of successfull edit of "my profile" form

The toast of succesfull edit was never shown (it was unimplemented)

image

image

###  The verification checkbox of the home preliminary form didn't do anything

Fixed the verification checkbox of the preliminary for on the home page, which didn't do anything. Now it disables the submit-button if it is unchecked and enables the submit-button when it's checked.

Now, after the fix, the submit button is inactive when the verification "is not given":

image

image

The required-input validation works in the text input fields as they should:

image

### CODE REVIEW

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr544.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-ui-pr544.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by karisal-anders — APPROVED** [review]

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr544.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-ui-pr544.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr544.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-ui-pr544.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Pull request merged**
