### PR TITLE
feat: cookie consent

### PR DESCRIPTION
**Pull request by melniiv**
## Context

KK-569 KK-570

### CODE REVIEW

**Review by nikomakela — CHANGES_REQUESTED** [review]
An error is thrown on every navigation call. It wasn't like that in #496 . My first expression was that it could be related to how the routes are created with react-router, but might be something else too.

https://github.com/City-of-Helsinki/kukkuu-ui/assets/389204/b6b0202a-25e7-4a6a-8ce8-3f0ec474408e

https://github.com/City-of-Helsinki/kukkuu-ui/assets/389204/212dbb4d-068a-4078-8402-573d69a50021

**Review by nikomakela — APPROVED** [review]

**Comment by nikomakela** [comment]
I rebased this to the master instead of `KK-1017-vite` branch. Now the test automations will be ran and the review server will be built. 

I also tested that the branch is not relying to Vite any how and it is not conflicting with the Vite changes. Tested the cookie consent locally and it's working OK! 👏

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr497.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr497.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
