### PR TITLE
KK-513 | Add option to subscribe to notifications for available places

### PR DESCRIPTION
**Pull request by Jokinen**
### Context

This PR makes it possible for users to sign up to be notified when places to full events become available.

https://futuricedesigners.invisionapp.com/share/QZYQWJSFRMW#/431508302_Ilmoittautuminen_Onnistui_Copy_3

### Code

This PR bloated a bit.

- I adjusted the design of the Enrol page to make it align better with the design
- I went through some pain trying to write tests
    * I upgraded Apollo
    * I added testing library
    * And the issues still persisted (fml)
- I added a `useMutation` hook that offers a default `onError` handler
- I refactored the `Enrol` component into `EnrolPage` and `Enrol` in order to make it possible to give some test coverage without having to mock too much of the API

### Testing

I added integration tests for `Enrol` and `EventOccurrence` components.

### CODE REVIEW

**Review by tuovinensanttu — APPROVED** [review]
There's quite a lot of stuff here, but it's all looking good 👍 . Also tested the new functionality and it seems to be working as expected. Nice work overall!

**Comment by Jokinen** [comment]
We decided to handle KK-560 by adjusting the text content in this view when an occurrence is full.

For transparency, this PR is waiting for the backend features to be ready before it's merged

**Comment by Jokinen** [comment]
Added #311 into this branch which contains minor fixes and KK-560.

**Comment by Jokinen** [comment]
Rebased to resolve merge conflicts.

**Pull request merged**
