### PR TITLE
KK-1065 | refactor: refactor types from 4ea1fea06e1b34b7825bcfa65036a60db78a27d6

### PR DESCRIPTION
**Pull request by karisal-anders**
### refactor: refactor types from 4ea1fea06e1b34b7825bcfa65036a60db78a27d6

 - refactor types for clarity / maintenance
   - move to own files
   - deduplicate
   - rename
   - rename /type/ folders to /types/ folders for consistency

refs KK-1065

## Context

[KK-1065](https://helsinkisolutionoffice.atlassian.net/browse/KK-1065)

## Screenshots

[KK-1065]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr515.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — APPROVED** [review]

**Review by nikomakela — COMMENTED** [review]
It would be good to use the generated types instead, as much as we can.

**Comment by karisal-anders** [comment]
> It would be good to use the generated types instead, as much as we can.

I agree, let's see if that can be done. More refactoring!

**Pull request merged**
