### PR TITLE
fix: navigation render without data fetched

### PR DESCRIPTION
**Pull request by melniiv**
## Context

[KK-1188](https://helsinkisolutionoffice.atlassian.net/browse/KK-1188)

## Screenshots

[KK-1188]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr590.dev.hel.ninja :laughing::tada::tada::tada:

**Review by nikomakela — APPROVED** [review]

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr590.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr590.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr590.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr590.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
