### PR TITLE
KK-1030 | feat(logos): add Tiedemuseo Liekki & update Hotelli- ja ravintolamuseo

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat(logos): add Tiedemuseo Liekki & update Hotelli- ja ravintolamuseo

also:
 - add cross-env and use it to make "yarn test" cross-platform compatible

refs KK-1030

## Context

[KK-1030](https://helsinkisolutionoffice.atlassian.net/browse/KK-1030)

#### Finnish
fi

#### Swedish
sv

#### English
en

#### Finnish
fi-zoom

#### Swedish
sv-zoom

#### English
en-zoom

#### Hotelli- ja ravintolamuseo
hotelli-ja-ravintolamuseo

[KK-1030]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-ui-pr488.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by nikomakela — APPROVED** [review]
good! 👌

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr488.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
