### PR TITLE
KK-1096,1104 | fix: logos and translations

### PR DESCRIPTION
**Pull request by melniiv**
## Context

[jira-id](https://helsinkisolutionoffice.atlassian.net/browse/<jira-id>)

### CODE REVIEW

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr539.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-ui-pr539.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by nikomakela — APPROVED** [review]
a bit weird on mobile, but acceptable. Check the comment by @karisal-anders

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr539.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
