### PR TITLE
chore: review tunnistamo

### PR DESCRIPTION
**Pull request by terovirtanen**
## Description

Use local tunnistamo instance instead of KuVa test tunnistamo

Pipeline template changes are [kukkuu-pipelines/pullrequest/5475](https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines/pullrequest/5475)

[Tunnistamo instance on review environment](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/DD/pages/8343355463/Tunnistamo+instance+on+review+environment)

## Context

[DEVOPS-545](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-545)

## Screenshots

[DEVOPS-545]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr484.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr484.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr484.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr484.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr484.dev.hel.ninja :laughing::tada::tada::tada:

**Review by karisal-anders — APPROVED** [review]

**Comment by terovirtanen** [comment]
## TestCafe result is __failed__ for https://kukkuu-ui-pr484.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Pull request merged**
