### PR TITLE
fix(dockerfile): add REACT_APP_ADMIN_TICKET_VALIDATION_URL argument

### PR DESCRIPTION
**Pull request by karisal-anders**
### fix(dockerfile): add REACT_APP_ADMIN_TICKET_VALIDATION_URL argument

"Start build for kukkuu-ui" in kukkuu-ui v1.4.0's production release's pipeline gave warning:
 - [Warning] one or more build args were not consumed: [REACT_APP_ADMIN_TICKET_VALIDATION_URL]

This should fix the above warning.

refs KK-1030 (noticed warning when building production release image)

## Context

[KK-1030](https://helsinkisolutionoffice.atlassian.net/browse/KK-1030)

## Screenshots

[KK-1030]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr489.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr489.dev.hel.ninja :laughing::tada::tada::tada:

**Review by nikomakela — APPROVED** [review]

**Review by terovirtanen — APPROVED** [review]
technical ok

**Pull request merged**
