### PR TITLE
fix: dockerfile base on ubi image DEVOPS-560

### PR DESCRIPTION
**Pull request by terovirtanen**
## Description
Use ubi image as base

Helsinki-City ubi instructions
[Container images and Dockerfiles](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/OS/pages/8298496186/Container+images+and+Dockerfiles)

## Context

[DEVOPS-560](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-560)

## Screenshots

[DEVOPS-560]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr486.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr486.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr486.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr486.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr486.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr486.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by nikomakela** [comment]
Similar, but commented: https://github.com/City-of-Helsinki/kukkuu/pull/329

**Review by nikomakela — APPROVED** [review]

**Review by karisal-anders — COMMENTED** [review]
The magic numbers should be changed to usernames where possible in the Dockerfile IMO before merging this as was done in https://github.com/City-of-Helsinki/kukkuu/pull/329

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-local.api.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**KUKKUU-UI branch is deployed to platta: https://kukkuu-ui-pr486.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## TestCafe result is __success__ for https://kukkuu-ui-pr486.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
