### PR TITLE
Pipeline yaml files and port updates

### PR DESCRIPTION
**Pull request by Vitals9367**
## Context

[jira-id](https://helsinkisolutionoffice.atlassian.net/browse/<jira-id>)

### CODE REVIEW

**Comment by charn** [comment]
Since the port of the service is changed (and since we're still running this in a different environment) this would also need a change in configurations for the current in-use environments:
- [review](https://github.com/City-of-Helsinki/kukkuu-ui/blob/master/.github/workflows/review.yml#L14), [staging](https://github.com/City-of-Helsinki/kukkuu-ui/blob/master/.github/workflows/staging.yml#L17) and [production](https://github.com/City-of-Helsinki/kukkuu-ui/blob/master/.github/workflows/production.yml#L16) configuration.

`SERVICE_PORT: 80` -> `SERVICE_PORT: 8080`

**Comment by Vitals9367** [comment]
Changed service port to 8080

**Review by nikomakela — APPROVED** [review]
looks good to me, but I have no experience with these

**Comment by nikomakela** [comment]
Is there a good reason why the builds fails?

**Comment by Jokinen** [comment]
The build likely fails because of permissions. The account of the person opening the PR has to have enough privileges, e.g. be a member of City of Helsinki, or some group within it.

**Pull request merged**
